spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowCredentials: true
            allowedHeaders: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes[2]:
        uri: lb://profile-ms
        predicates[1]: Method=POST
        id: profile-ms-login
        predicates[0]: Path=/api/v1/login
      routes[0]:
        id: profile-ms-get-update-delete-post-patch
        filters[1]: RemoveRequestHeader=Cookie
        predicates[0]: Path=/api/v1/profiles/**
        filters[0]: AuthorizationHeaderFilter
        predicates[1]: Method=GET,PUT,DELETE,POST,PATCH
        uri: lb://profile-ms
      routes[1]:
        id: profile-ms-register
        predicates[1]: Method=POST
        uri: lb://profile-ms
        predicates[0]: Path=/api/v1/register
      routes[3]:
        id: profile-ms-interests-get-update-delete
        filters[1]: RemoveRequestHeader=Cookie
        predicates[0]: Path=/api/v1/interests/**
        filters[0]: AuthorizationHeaderFilter
        predicates[1]: Method=GET,PUT,DELETE,POST
        uri: lb://profile-ms
      routes[4]:
        id: profile-ms
        uri: lb://profile-ms
        predicates: Path=/profile/v2/api-docs
      routes[5]:
        id: chat-ms
        uri: lb://chat-ms
        predicates: Path=/chat/v2/api-docs
      routes[6]:
        id: chat-ms-websocket
        uri: lb://chat-ms
        predicates: Path=/ws/**
      routes[7]:
        id: chat-ms-rest
        uri: lb://chat-ms
        filters[0]: AuthorizationHeaderFilter
        predicates: Path=/messages/**
      routes[8]:
        id: image-ms-rest
        uri: lb://image-ms
        filters[0]: AuthorizationHeaderFilter
        predicates[0]: Path=/api/v1/images/**
        predicates[1]: Method=GET,PUT,DELETE,POST,PATCH
      routes[9]:
        id: image-ms
        uri: lb://image-ms
        predicates: Path=/image/v2/api-docs
      routes[10]:
        id: notification-ms-websocket
        uri: lb://notification-ms
#        filters[0]: AuthorizationHeaderFilter
        predicates: Path=/notification/**
  main:
    allow-bean-definition-overriding: 'true'
  application:
    name: api-gateway
server:
  port: '8080'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
token:
  secret: 8FF6841EC2DD8EA5B855B1C1EC3CA

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

