global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'profile_ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['profile_ms:8080']
        labels:
          application: 'Profile Microservice Application'
  - job_name: 'chat_ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['chat_ms:8080']
        labels:
          application: 'Chat Microservice Application'
  - job_name: 'image_ms'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['image_ms:8080']
        labels:
          application: 'Image Microservice Application'
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
        labels:
          application: 'Api Gateway Application'