server:
  port: 0

spring:
  kafka:
    bootstrap-servers: broker:29092
  application:
    name: profile-ms
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_db:3306/prof?createDatabaseIfNotExist=true
    username: root
    password: root

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8081/eureka



springfox:
  documentation:
    swagger:
      v2:
        path: /profile/v2/api-docs
