server:
  port: 0
#
spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:com.madikhan.profilemicro.model.event.Notification
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: profile-ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prof?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


login:
  uri:
    path: /api/v1/login

token:
  secret: 8FF6841EC2DD8EA5B855B1C1EC3CA
  expiration:
    time: 8640000000

springfox:
  documentation:
    swagger:
      v2:
        path: /profile/v2/api-docs


management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

