server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.madikhan.notification.event.Notification
          deserializer:
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notificationId
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: notification-ms
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka


springfox:
  documentation:
    swagger:
      v2:
        path: /notification/v2/api-docs


management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
